# Generated by Django 4.2.18 on 2025-01-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_workspace_editors_user_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=8)),
                ('civil_id', models.CharField(max_length=12, unique=True)),
                ('diagnosis', models.TextField()),
                ('procedure', models.TextField()),
                ('side', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('waiting', 'Waiting'), ('past', 'Past'), ('deleted', 'Deleted')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_bookings', to='core.workspace')),
            ],
        ),
    ]
