# Generated by Django 5.1.5 on 2025-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clinicappointment_civil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='civil_id',
            field=models.CharField(default=284021200148, max_length=12),
            preserve_default=False,
        ),
    ]
