# Generated by Django 5.1.5 on 2025-01-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinicappointment_civil_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicappointment',
            old_name='civil_id',
            new_name='civil_id2',
        ),
    ]
