# Generated by Django 5.1.5 on 2025-01-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_civil_id_clinicappointment_civil_id2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicappointment',
            old_name='civil_id2',
            new_name='civil_id',
        ),
    ]
