# Generated by Django 4.2.18 on 2025-01-26 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_surgicalbooking_civil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='days_open',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workspace',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ClinicAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('confirmed', models.BooleanField(default=False)),
                ('appointment_type', models.CharField(choices=[('New', 'New'), ('Follow-Up', 'Follow-Up')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.workspace')),
            ],
        ),
    ]
