# Generated by Django 5.1.5 on 2025-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_civil_id2_clinicappointment_civil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicappointment',
            name='confirmed',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Unknown', max_length=50),
        ),
    ]
