# Generated by Django 4.2.18 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workspace_days_open_workspace_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='referral_letter',
            field=models.ImageField(blank=True, null=True, upload_to='referral_letters/'),
        ),
    ]
