# Generated by Django 4.2.18 on 2025-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_workspace_days_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='days_open',
            field=models.JSONField(default=list),
        ),
    ]
