# Generated by Django 5.1.5 on 2025-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='maximum',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
