# Generated by Django 5.1.5 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workspace_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='system_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workspaces', models.ManyToManyField(blank=True, related_name='specialities', to='core.workspace')),
            ],
        ),
    ]
