# Generated by Django 5.1.5 on 2025-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clinicappointment_system_referral_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='maimum_new_referrals',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
