# Generated by Django 5.1.5 on 2025-05-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workspace_maimum_new_referrals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='maimum_new_referrals',
            new_name='maximum_new_referrals',
        ),
    ]
