# Generated by Django 5.1.5 on 2025-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
