# Generated by Django 5.1.5 on 2025-05-02 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_workspace_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='clinicappointment',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
