# Generated by Django 5.1.5 on 2025-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clinicappointment_booked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
