# Generated by Django 5.1.5 on 2025-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_speciality_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clerk',
            field=models.BooleanField(default=False),
        ),
    ]
