# Generated by Django 5.1.5 on 2025-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_doctor_clerk'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalbooking',
            name='photo_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='surgical_attachments/'),
        ),
    ]
