# Generated by Django 5.1.5 on 2025-05-09 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_surgicalbooking_photo_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 9, 21, 26, 43, 872243, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
