# Generated by Django 5.1.5 on 2025-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_clinicappointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalbooking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('sent_for_anesthesia', 'Sent for Anesthesia'), ('ready', 'Ready')], default='waiting', max_length=20),
        ),
    ]
