# Generated by Django 5.1.5 on 2025-05-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_surgicalbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('waiting', 'Waiting'), ('past', 'Past'), ('deleted', 'Deleted')], default='waiting', max_length=10),
        ),
    ]
