# Generated by Django 5.1.5 on 2025-05-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_surgicalbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalbooking',
            name='readiness',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('sent_for_anesthesia', 'Sent for Anesthesia'), ('ready', 'Ready')], default='waiting', max_length=50),
        ),
    ]
