# Generated by Django 5.1.5 on 2025-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_surgicalbooking_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalbooking',
            name='status2',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True),
        ),
    ]
