# Generated by Django 5.1.5 on 2025-05-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_surgicalbooking_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgicalbooking',
            name='status2',
        ),
    ]
