# Generated by Django 5.1.5 on 2025-06-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_favoritepatient_favoritepatientnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='session',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lock',
            name='session',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='session_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='surgicalbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('waiting', 'Waiting'), ('past', 'Past'), ('deleted', 'Deleted')], default='waiting', max_length=20),
        ),
    ]
