# Generated by Django 5.1.5 on 2025-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_clinicappointment_session_lock_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='pm',
            field=models.BooleanField(default=False),
        ),
    ]
