# Generated by Django 5.1.5 on 2025-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_lock_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='give_new_referrals_time',
            field=models.BooleanField(default=True),
        ),
    ]
