# Generated by Django 5.1.5 on 2026-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_workspace_give_new_referrals_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='allow_consultant_selection',
            field=models.BooleanField(default=False, help_text='Allow referrers to choose the consultant who receives their referral.'),
        ),
    ]
