# Generated by Django 5.1.5 on 2026-09-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_speciality_allow_consultant_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
